easy_admin:
  site_name: 'SLZ-CAA <em style="font-size: 80%;">Admin.</em>'
  list:
    max_results: 30
  design:
    brand_color: '#00134a'
    form_theme: 'vertical'
    menu:
      - { label: 'Links' }
      - { label: 'Metadata' }
      - { entity: 'Asl', icon: 'tags', label: 'Asl' }
      - { entity: 'Fachbezug', icon: 'tags', label: 'Fachbezügen' }
      - { entity: 'Fertigkeit', icon: 'tags', label: 'Fertigkeiten' }
      - { entity: 'Medium', icon: 'tags', label: 'Media' }
      - { entity: 'Sprache', icon: 'tags', label: 'Sprachen' }
      - { entity: 'Sprachniveau', icon: 'tags', label: 'Zielstufen' }