easy_admin:
  entities:
    Ausgangssprache:
      class: AppBundle\Entity\Ausgangssprache
      label: 'Ausgangssprachen'
      list:
        title: '%%entity_label%%'
        sort: ['code', 'ASC']
        fields:
          - 'code'
          - 'de'
          - 'en'
          - 'fr'