easy_admin:
  entities:
    Lernformate:
      class: AppBundle\Entity\Lernmaterialformate
      label: 'Lernformate'
      list:
        title: '%%entity_label%%'
        sort: ['de', 'ASC']
        fields:
          - 'de'
          - 'en'
          - 'fr'