easy_admin:
  entities:
    Link:
      class: AppBundle\Entity\Link
      label: 'Link'
      list:
        title: '%%entity_label%%'
        sort: ['updatedAt', 'DESC']
        fields:
          - 'name'
          - { property: 'updatedAt', label: 'Update' }
      form:
        fields:
          - { type: 'group', css_class: 'col-sm-9' }
          - name
          - url
          - { property: 'description', label: 'Beschreibung' }
          - { type: 'group', css_class: 'col-sm-3' }
          - sprache
          - ausgangssprache
          - asl
          - fachbezug
          - fertigkeit
          - { property: 'lernmaterialformate', label: 'Lernformate' }
          - sprachniveau