easy_admin:
  entities:
    Medium:
      class: AppBundle\Entity\Medium
      label: 'Medium'
      list:
        title: '%%entity_label%%'
        sort: ['code', 'ASC']
        fields:
          - 'code'
          - 'de'
          - 'en'
          - 'fr'